apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-otterize
  region: us-east-2
  version: "1.27"

nodeGroups:
  - name: ng-1
    instanceType: m5.large
    desiredCapacity: 1
  - name: ng-2
    instanceType: m5.xlarge
    desiredCapacity: 1
